# Generated by Django 5.0.8 on 2024-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
